#!/usr/bin/env bash
# -*- ENCODING: UTF-8 -*-
##
## @author     Raúl Caro Pastorino
## @copyright  Copyright © 2018 Raúl Caro Pastorino
## @license    https://wwww.gnu.org/licenses/gpl.txt
## @email      raul@fryntiz.dev
## @web        https://fryntiz.es
## @gitlab     https://gitlab.com/fryntiz
## @github     https://github.com/fryntiz
## @twitter    https://twitter.com/fryntiz

## Referencia oficial: http://i3wm.org/docs/userguide.html

## Iconos de ejemplo:
##                                    
##                                 
##                     

## Tecla modificadora
set $mod Mod4

## Nombre de monitores 1 y 2:
set $mon1 $DISPLAY0_NAME
set $mon2 $DISPLAY1_NAME
set $mon3 $DISPLAY2_NAME

## Configuración
set $coordenadas '36.7349439:-6.4253577'  ## Coordenadas

###########################################################
############        Espacios de trabajo        ############
###########################################################
## Nombres para cada espacio del monitor 1
set $WS1 1:
set $WS2 2:
set $WS3 3:
set $WS4 4:
set $WS5 5:
set $WS6 6:
set $WS7 7:
set $WS8 8:

## Nombres para cada espacio del monitor 2
set $WS9 9:
set $WS10 10:

## Asigno workspaces a Monitor 1
#workspace 1 output $mon1
#workspace 2 output $mon1
#workspace 3 output $mon1
#workspace 4 output $mon1
#workspace 5 output $mon1
#workspace 6 output $mon1
#workspace 7 output $mon1
#workspace 8 output $mon1

## Asigno workspaces a Monitor 2
workspace $WS9 output $mon2
workspace $WS10 output $mon2

## Cargando desde JSON
## Generar: i3-save-tree --workspace 2:TERM > ~/.config/i3/workspace_2.json
## Limpiar: tail -n +2 ~/.config/i3/Workspaces/workspace_2.json | fgrep -v '// splitv' | sed 's|//||g' > ~/.config/i3/Workspaces/workspace_2.json

#exec --no-startup-id ~/.config/i3/Workspaces/load_layouts.sh

## Establecer monitores HDMI al conectarse:
#exec --no-startup-id xrandr --output eDP1-1 --primary
#exec --no-startup-id xrandr --output HDMI-1 --secundary

###########################################################
############ Ubicacion de ventanas por defecto ############
###########################################################

## 2
assign [class="[pP]hp[sS]torm"] → $WS2
for_window [class="[pP]hp[sS]torm"] focus
assign [class="[pP]y[cC]harm"] → $WS2
for_window [class="[pP]y[cC]harm"] focus
assign [class="[wW]eb[sS]torm"] → $WS2
for_window [class="[pP]y[cC]harm"] focus
assign [class="^[aA]tom"] → $WS2
for_window [class="^[aA]tom"] focus
assign [class="^[bB]rackets"] → $WS2
for_window [class="^[Bb]rackets"] focus
assign [class="[vV][sS][cC]odium"] → $WS2
for_window [class="[vV][sS][cC]odium"] focus

## 3
assign [class="^[fF]irefox"] → $WS3
for_window [class="^[fF]irefox"] focus
assign [class="^[cC]hrome"] → $WS3
for_window [class="^[cC]hrome"] focus
assign [class="^[cC]hromium"] → $WS3
for_window [class="^[cC]Chromium"] focus
assign [class="^[gG]oogle-chrome"] → $WS3
for_window [class="^[gG]oogle-chrome"] focus
assign [class="[tT]orbrowser|[tT]orbrowser-launcher"] → $WS3
for_window [class="[tT]orbrowser|[tT]orbrowser-launcher"] focus

## 4
assign [class="[tT]hunderbird|[eE]volution"] → $WS4
for_window [class="[tT]hunderbird|[eE]volution"] focus
assign [class="^Corebird"] → $WS4
for_window [class="^Corebird"] focus
assign [class="[tT]elegram"] → $WS4
for_window [class="[tT]elegram"] focus
assign [class="[wW]hatsie|[wW]hatsapp"] → $WS4
for_window [class="[wW]hatsie|[wW]hatsapp"] focus

## 5
assign [class="^Gimp"] → $WS5
for_window [class="^Gimp"] focus
assign [class="^Inkscape"] → $WS5
for_window [class="^Inkscape"] focus
assign [class="^Dia"] → $WS5
for_window [class="^Dia"] focus
assign [class="kdenlive|openshot-qt|openshot|cinelerra"] → $WS5
for_window [class="^kdenlive|openshot-qt|openshot|cinelerra"] focus
assign [class="^Darktable"] → $WS5
for_window [class="^Darktable"] focus

## 6
assign [class="^Audacity"] → $WS6
for_window [class="^Audacity"] focus
assign [class="^Rhythmbox"] → $WS6
for_window [class="^Rhythmbox"] focus

## 7
assign [class="VirtualBox|Vmplayer"] → $WS7
for_window [class="VirtualBox|Vmplayer"] focus
assign [class="Oracle VM VirtualBox"] → $WS7
for_window [class="Oracle VM VirtualBox"] focus

## 8
assign [class="Pychess"] → $WS7
for_window [class="Pychess"] focus

###########################################################
############         FOCUS DE VENTANAS         ############
###########################################################
bindsym $mod+F1 [class="Firefox"] focus
bindsym $mod+F2 [class="PhpStorm"] focus
bindsym $mod+F3 [title="Atom"] focus
#bindsym $mod+F4 [class="nautilus"] focus
#bindsym $mod+F5 [class="tilix"] focus
#bindsym $mod+F6 [title="PyCharm"] focus
#bindsym $mod+F7 [class="Firefox"] focus
#bindsym $mod+F8 [class="Firefox"] focus
#bindsym $mod+F9 [class="Firefox"] focus
#bindsym $mod+F10 [class="Thunderbird"] focus
#bindsym $mod+F11 [class="whatsie"] focus
#bindsym $mod+F12 [class="Telegram"] focus

###########################################################
############       Visualización/Pantalla      ############
###########################################################
## Establezco a 90 dpi
#exec --no-startup-id xrandr --dpi 90
#exec_always --no-startup-id xrandr --dpi 90
exec --no-startup-id xrandr --dpi $DPI
exec_always --no-startup-id xrandr --dpi $DPI


## Fuente para títulos de ventanas usadas en bar {} block below.
font pango:monospace 8
#font pango:DejaVu Sans Mono 8

## Habilita o Deshabilita tener el foco al pasar el ratón
focus_follows_mouse no

## Usar Mouse+$mod para arrastrar ventanas flotantes
floating_modifier $mod

## Quita los bordes de los extremos de la pantalla
hide_edge_borders vertical

## Decoración de ventanas
##  Clase         Bordes   Fondo    Texto    Indicador
client.focused    #4c7899  #285577  #ffffff  #2e9ef4
client.unfocused  #4c7899  #24364F  #aaaaaa  #2e9ef4
client.focused    #c10101  #880404  #ffffff  #00AA00

## Modo de Organizar ventanas por defecto: default|stacking|tabbed
workspace_layout tabbed

# set trayer to be borderless
for_window [class="(?i)trayer"] border pixel 0

###########################################################
############   VENTANAS FLOTANTES POR DEFECTO  ############
###########################################################
## focus, floating, & sticky
## Pongo flotante ventanas de copiar, eliminar, mover y configuración
for_window [title="(?i)(?:copying|deleting|moving)"] floating enable
for_window [window_role="(?i)(?:pop-up|setup)"] floating enable

for_window [class="Galculator"] floating enable
for_window [class="Imagewriter"] floating enable
for_window [class="^Gpick$"] floating enable
for_window [class="^Gnome-font-viewer$"] floating enable
for_window [class="Lxappearance|lxappearance"] floating enable, move position 290 150
for_window [class="Nitrogen"] floating enable, move position 50 50
for_window [class="SimpleScreenRecorder"] floating enable
for_window [class="Kazam"] floating enable
for_window [class="System-config-printer"] floating enable
for_window [class="[tT]orbrowser-launcher$"] floating enable
for_window [class="Unetbootin"] floating enable
for_window [class="Usb-creator-gtk"] floating enable
for_window [class="Xfce4-taskmanager"] floating enable
for_window [title="^Terminator Preferences$"] floating enable
for_window [title="QOwnNotes"] floating enable, resize set 1000 800
for_window [title="ARandR"] floating enable, move position 50 50
for_window [title="^Screen Layout Editor$"] floating enable
for_window [title="^Instalador de paquetes"] floating enable, move position 50 50

###########################################################
############       VENTANAS NO FLOTANTES       ############
###########################################################

############################################################
###############            i3bar          ##################
############################################################
## Barra para monitor principal
bar {
    ## Monitor para información en la barra de estado
    #status_command  i3status        ## Mostrar status de monitoreo
    status_command  python3 ~/.config/i3pystatus/config.py

    ## Posición donde colocar la barra
    position        bottom           ## Posición Abajo

    ## Solo muestra applets/iconos en la barra principal
    tray_output primary
    #tray_output $mon1
    #tray_output $mon3
    #tray_output HDMI-0
    #tray_output DVI-I-1
    #tray_output LVDS-1
    #tray_output LVDS1


    ## Fuente
    #font pango:terminus, awesome 9
    #font pango:Inconsolata-dz for Powerline, ZektonLt Bold 11
    #font pango:DejaVu Sans Mono for Powerline Bold 11
    font pango:DejaVu Sans Mono for Powerline, PowerlineSymbols, FontAwesome, Linux Libertine Mono O Bold 11
    #font pango:Droid Sans Mono for Powerline 11
    #font pango:ZektonLt Bold 11
    #font pango:Inconsolata Nerd Font Complete Mono 10
    #font pango:Space Mono for Powerline 10

    workspace_buttons yes

    ## Salidas donde habilito esta barra
    output primary
    #output $mon2
    #output $mon1
    #output $mon3
    #output HDMI0
    #output HDMI-0
    #output DVI-I-1
    #output LVDS-1
    #output LVDS1
    #output HDMI-1

    ## Márgenes de iconos en la bandeja
    tray_padding 1

    ## Deshabilita el número en el nombre de los espacios de trabajo
    #strip_workspace_numbers yes

    colors {
        #background  #001111  ## Color del panel
        #statusline  #fdf6e3  ## Color del status
        #separator   #9e9e9e  ## Color de separadores
        #background  #1b1b1b
        #statusline  #ffffff
        #separator   #444444

        # Dark
        ## Colores           Bordes     Fondo      Texto
        #focused_workspace   #141414    #283232    #606060
        #active_workspace    #141414    #202020    #606060
        #inactive_workspace  #141414    #202020    #606060
        #urgent_workspace    #141414    #452828    #8c644c

        # Light
        ## Colores           Bordes     Fondo      Texto
        #focused_workspace   #dddddd    #ddbbdd    #606060
        #active_workspace    #dddddd    #dddddd    #606060
        #inactive_workspace  #dddddd    #dddddd    #606060
        #urgent_workspace    #dddddd    #452828    #8c644c

        ## Mi tema
        background #001111
        statusline #fdf6e3
        separator  #9e9e9e
        ## Colores           Bordes     Fondo      Texto
        focused_workspace   #FF0000    #FF0000    #FFFFFF
        active_workspace    #333333    #FFFFFF    #FF0000
        inactive_workspace  #001111    #285577    #C79A97
        urgent_workspace    #ffff00    #ffff00    #000000
        binding_mode        #2F343A    #900000    #FFFFFF
    }
}

## Barra solo visible en el segundo monitor
bar {
    output secundary
    output $mon2
    output HDMI1
    output HDMI-1
    output DVI-D-0
    output LVDS-2
    output VGA
    output VGA-1
    output DP-1
    output DP-2


    status_command  i3status
    #status_command  python3 ~/.config/i3/scripts/i3pystatus-min-config.py

    ## Deshabilitado iconos en esta segunda barra
    tray_output none

    font pango:Inconsolata-dz for Powerline  10

    ## Deshabilita el número en el nombre de los espacios de trabajo
    #strip_workspace_numbers yes

    colors {
        background  #001111  #Color del panel
        statusline  #fdf6e3  #Color del status
        separator   #9e9e9e  #Color de separadores

        ## Colores           Bordes     Fondo      Texto
        focused_workspace   #FF0000    #FF0000    #FFFFFF
        active_workspace    #333333    #FFFFFF    #FF0000
        inactive_workspace  #001111    #285577    #C79A97
        urgent_workspace    #ffff00    #ffff00    #000000
        binding_mode        #2F343A    #900000    #FFFFFF
    }
}

############################################################
#############     Bindings del Sistema    ##################
############################################################
## Navegar entre las ventanas $mod+[jkln] o $mod+[←↓→]
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+ntilde focus right
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

## Mover una ventana $mod+shift+[jkln] o $mod+shift+[←↓→]
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+ntilde move right
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

## Divide en orientación Horizontal
bindsym $mod+h split h; exec notify-send 'Horizontal'

## Divide en orientación Vertical
bindsym $mod+v split v; exec notify-send 'Vertical'

## Poner en pantalla completa la ventana actual con $mod+f
bindsym $mod+f fullscreen toggle; exec notify-send 'Pantalla completa'

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

## Alternar ventana entre flotante o tiling con $mod+Shift+space
bindsym $mod+Shift+space floating toggle

## Cambiar el foco entre tiling / floating windows
bindsym $mod+space focus mode_toggle

## El foco sobre el contenedor padre
bindsym $mod+a focus parent

## El foco sobre el contenedor hijo
#bindsym $mod+d focus child

## Recargar la configuración de pantalla actual
bindsym $mod+F5 exec ~/.config/i3/scripts/togglescreen.sh 'reload' 2> /tmp/test || notify-send 'Configuración de Pantallas no aplicable'


## Conmutar entre configuraciones de pantalla para varios monitores
bindsym $mod+F6 exec ~/.config/i3/scripts/togglescreen.sh 2> /tmp/test && notify-send 'Cambio de pantallas' || notify-send 'Configuración de Pantallas no aplicable'

## Cambiar entre espacioes de trabajo
bindsym $mod+1 workspace $WS1
bindsym $mod+2 workspace $WS2
bindsym $mod+3 workspace $WS3
bindsym $mod+4 workspace $WS4
bindsym $mod+5 workspace $WS5
bindsym $mod+6 workspace $WS6
bindsym $mod+7 workspace $WS7
bindsym $mod+8 workspace $WS8
bindsym $mod+9 workspace $WS9
bindsym $mod+0 workspace $WS10

## Mover una ventana a un espacio de trabajo concreto
bindsym $mod+Shift+1 move container to workspace $WS1
bindsym $mod+Shift+2 move container to workspace $WS2
bindsym $mod+Shift+3 move container to workspace $WS3
bindsym $mod+Shift+4 move container to workspace $WS4
bindsym $mod+Shift+5 move container to workspace $WS5
bindsym $mod+Shift+6 move container to workspace $WS6
bindsym $mod+Shift+7 move container to workspace $WS7
bindsym $mod+Shift+8 move container to workspace $WS8
bindsym $mod+Shift+9 move container to workspace $WS9
bindsym $mod+Shift+0 move container to workspace $WS10

bindsym $mod+x workspace next ## Siguiente workspace
bindsym $mod+z workspace prev ## Anterior workspace
bindsym Mod1+Ctrl+Right workspace next
bindsym Mod1+Ctrl+Left workspace prev

## Redimensionar ventana (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym ntilde resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        ## Para volver al modo normal introducir: Enter o Escape
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

## Entrar al modo para redimensionar
bindsym $mod+r mode "resize"

## Abrir terminal con $mod+Intro
#bindsym $mod+Return exec ~/.config/i3/scripts/i3-shell.sh
bindsym $mod+Return exec i3-sensible-terminal

## Cerrar ventana actual con $mod+shift+q
bindsym $mod+Shift+q kill

## Abrir dmenu (Lanzador de programas)
#bindsym $mod+d exec i3-dmenu-desktop ## Antes dmenu_run
bindsym $mod+d exec j4-dmenu-desktop

#bindsym $mod+shift+d exec rofi -combi-modi window,drun,ssh -theme Paper -font "hack 10" -show combi
bindsym $mod+m exec --no-startup-id ~/.config/i3/scripts/rofr.sh -r
bindsym $mod+shift+d exec --no-startup-id ~/.config/i3/scripts/rofr.sh -r

############################################################
#############       Bindings Propios      ##################
############################################################
## Alternar entre teclado "es-querty" y "dvorak"
bindsym $mod+Control+space exec --no-startup-id ~/.config/i3/scripts/keyboard.sh

## Captura un área de la pantalla seleccionada al portapapeles
bindsym --release shift+Print exec xfce4-screenshooter -crm

## Captura un área de la pantalla a Imágenes
bindsym --release Control+shift+Print exec xfce4-screenshooter -rm -s ~/Imágenes/Screenshots/

## Captura de Ventana actual
bindsym --release $mod+print exec xfce4-screenshooter -wm -s ~/Imágenes/Screenshots/

## Captura de Pantalla Completa al portapapeles
bindsym --release $mod+shift+print exec xfce4-screenshooter -cfm

## Captura de Pantalla Completa
bindsym --release print exec xfce4-screenshooter -fm -s ~/Imágenes/Screenshots/

## Brillo de la pantalla
bindsym XF86MonBrightnessUp exec --no-startup-id brightnessctl s $(($(brightnessctl g) + 5000))
bindsym XF86MonBrightnessDown exec --no-startup-id brightnessctl s $(($(brightnessctl g) - 5000))

## Brillo de pantalla por defecto al 60%
exec --no-startup-id brightnessctl s 72000

#bindcode XF86MonBrightnessUp exec --no-startup-id xbacklight -inc 10
#bindcode XF86MonBrightnessDown exec --no-startup-id xbacklight -dec 10
#bindcode XF86MonBrightnessUp exec --no-startup-id ~/config/.i3/scripts/brillo.py next && notify-send "Brillo Arriba" || notify-send "Error: Brillo Arriba ha fallado"
#bindcode XF86MonBrightnessDown exec --no-startup-id ~/config/.i3/scripts/brillo.py back && notify-send "Brillo Abajo" || notify-send "Error: Brillo Abajo ha fallado"

## Abrir programa de Notas QOwnNotes
bindsym --release $mod+n exec QOwnNotes

## Abrir gestor de contraseñas KeePass2
bindsym --release $mod+k exec keepass2 "$HOME/Documentos/Personal.kdbx"

############################################################
###############          Autostart        ##################
############################################################
exec --no-startup-id i3-msg 'workspace $WS1; exec nautilus;'
exec --no-startup-id i3-msg 'workspace $WS1; exec tilix;'
exec --no-startup-id i3-msg 'workspace $WS3; exec x-www-browser; workspace $WS1'
exec --no-startup-id i3-msg 'workspace $WS4; exec ~/4_Programas/Telegram/Telegram; workspace $WS1'
#exec --no-startup-id i3-msg 'workspace $WS4; exec corebird; workspace $WS1'
#exec --no-startup-id i3-msg 'workspace $WS4; exec whatsie; workspace $WS1'
#exec --no-startup-id i3-msg 'workspace $WS4; exec thunderbird; workspace $WS1'

## Fondo de pantalla nitrogen
exec --no-startup-id nitrogen --restore

## Portapapeles parcellite
#exec --no-startup-id parcellite

#Portapapeles de XFCE (permite guardar capturas de pantalla): xfce4-clipman
exec --no-startup-id xfce4-clipman

## Mensajes emergentes
exec --no-startup-id dunst

## Ocultar ratón tras inactividad
exec --no-startup-id unclutter -idle 1

## Configuraciones para X
exec --no-startup-id xrdb -load ~/.Xresources

## Authentication agent
exec --no-startup-id lxpolkit

## Temperatura de pantalla según zona y hora
#exec --no-startup-id redshift -l $coordenadas -t 5500:4500

## Servidor de audio Pulseaudio
exec --no-startup-id pulseaudio --start

## Bluetooth
exec --no-startup-id blueman-applet

## Configura el touchpad para habilitar teclas y toques con 1,2 y 3 dedos.
# - 1 dedo click izquierdo
# - 2 dedos click derecho
# - 3 dedos click central
## Establezco configuración al cargar y a los 90 segundos, a veces fallaba...
exec --no-startup-id synclient EmulateMidButtonTime=1 TouchpadOff=0 VertTwoFingerScroll=1 HorizTwoFingerScroll=1 VertEdgeScroll=1 TapButton1=1 TapButton2=3 TapButton3=2 ClickFinger1=1 ClickFinger2=2 ClickFinger3=3
exec --no-startup-id sleep 90 && synclient EmulateMidButtonTime=1 TouchpadOff=0 VertTwoFingerScroll=1 HorizTwoFingerScroll=1 VertEdgeScroll=1 TapButton1=1 TapButton2=3 TapButton3=2 ClickFinger1=1 ClickFinger2=2 ClickFinger3=3
#exec_always --no-startup-id sleep 3 && synclient EmulateMidButtonTime=1 TouchpadOff=0 VertTwoFingerScroll=1 HorizTwoFingerScroll=1 VertEdgeScroll=1 TapButton1=1 TapButton2=3 TapButton3=2 ClickFinger1=1 ClickFinger2=2 ClickFinger3=3

exec --no-startup-id xbindkeys
exec_always --no-startup-id xbindkeys

## Ejemplos o ideas
#exec_always --no-startup-id al-polybar-session
#exec --no-startup-id xfsettingsd
#exec --no-startup-id lxpolkit
#exec --no-startup-id xset r rate 250 30
#exec --no-startup-id setxkbmap -option "ctrl:swapcaps" #Cambia bloq Mayus y CTRL
#exec --no-startup-id xflux -l 36.7756 -g -6.3616 -k 4200
#exec --no-startup-id ksuperkey -e 'Super_L=Alt_L|F1'

############################################################
###############    EJECUTAR AL RECARGAR   ##################
############################################################
## Fondo de pantalla nitrogen
exec_always --no-startup-id nitrogen --restore
exec_always --no-startup-id dunst


exec --no-startup-id cp ~/.Xresources /tmp/.Xresources && echo "Xft.dpi: $DPI" >> /tmp/.Xresources && xrdb -load /tmp/.Xresources
exec_always --no-startup-id cp ~/.Xresources /tmp/.Xresources && echo "Xft.dpi: $DPI" >> /tmp/.Xresources && xrdb -load /tmp/.Xresources


############################################################
###############  MENÚ DE APAGADO/BLOQUEO  ##################
############################################################
set $mode_system Sistema: (l) Bloquear, (e) Salir, (s) Suspender, (h) Hibernar, (r) Reiniciar, (Shift+s) Apagar

set $i3exit ~/.config/i3/scripts/i3exit.sh

mode "$mode_system" {
    bindsym l exec --no-startup-id $i3exit lock, mode "default"
    bindsym e exec --no-startup-id $i3exit logout, mode "default"
    bindsym s exec --no-startup-id $i3exit suspend, mode "default"
    bindsym h exec --no-startup-id $i3exit hibernate, mode "default"
    bindsym r exec --no-startup-id $i3exit reboot, mode "default"
    bindsym Shift+s exec --no-startup-id $i3exit shutdown, mode "default"

    # back to normal: Enter or Escape
    bindsym Return mode "default"
    bindsym Escape mode "default"
}

bindsym $mod+Escape mode "$mode_system"

############################################################
###############    MENÚ DE SERVIDORES     ##################
############################################################
set $mode_servers A.Apache: (1), E.Apache: (2), A.MariaDB: (3), E.MariaDB: (4), A.PostgreSQL: (5), E.PostgreSQL: (6)

set $servers ~/.config/i3/scripts/servers.sh

mode "$mode_servers" {
    bindsym 1 exec --no-startup-id $servers apache start, mode "default"
    bindsym 2 exec --no-startup-id $servers apache stop, mode "default"
    bindsym 3 exec --no-startup-id $servers mariadb start, mode "default"
    bindsym 4 exec --no-startup-id $servers mariadb stop, mode "default"
    bindsym 5 exec --no-startup-id $servers postgresql start, mode "default"
    bindsym 6 exec --no-startup-id $servers postgresql stop, mode "default"

    # back to normal: Enter or Escape
    bindsym Return mode "default"
    bindsym Escape mode "default"
}

bindsym $mod+F12 mode "$mode_servers"

############################################################
###############           APPLETS         ##################
############################################################
## Dropbox
#exec --no-startup-id dropbox start

## Synology Drive
exec --no-startup-id synology-drive

## Nextcloud
#exec --no-startup-id nextcloud

## pCloud
exec --no-startup-id "$HOME/AppImage/pcloud"

## Red
exec --no-startup-id nm-applet

## Transparencias de ventanas y menús mediante Compton
#exec --no-startup-id compton -cCGb

## Teclado Numérico
exec --no-startup-id numlockx on

## Applet de Volumen
exec --no-startup-id volumeicon

## Applet de Firewalld
exec --no-startup-id firewall-applet

## Applet de Impresora
#exec --no-startup-id system-config-printer-applet

############################################################
##############   Recargar/Bloquear/Salir    ################
############################################################
## Recargar el archivo de configuración
bindsym $mod+Shift+c reload

## Reiniciar i3 conservando la sesión
bindsym $mod+Shift+r restart

## Salir de i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'Si pulsas sobre salir se cerrará todo lo que tengas abierto. ¿Realmente quieres salir?' -b 'Si, exit i3' 'i3-msg exit'"

## Suspender al pulsar botón de apagado
bindsym PowerOff exec --no-startup-id i3lock; pm-suspend

## Bloquear pantalla
bindsym $mod+p exec "~/.config/i3/scripts/lock_and_blur.sh"
exec xautolock -detectsleep -time 15 -locker "~/.config/i3/scripts/lock_and_blur
.sh" -notify 30 -notifier "notify-send -u critical -t 10000 -- 'Bloqueando pantalla en 30 segundos'"

###########################################################
############         TECLAS MULTIMEDIA         ############
###########################################################
## Mostrar todas las teclas y codigos → xmodmap -pke y
## Alsamixer controles
bindsym XF86AudioRaiseVolume exec --no-startup-id amixer set Master 10%+
bindsym XF86AudioLowerVolume exec --no-startup-id amixer set Master 10%-
bindsym XF86AudioMute exec --no-startup-id amixer set Master toggle

# Touchpad controls
#bindsym XF86TouchpadToggle exec /some/path/toggletouchpad.sh # toggle touchpad

# Media player controls
bindsym XF86AudioPlay exec playerctl play && "notify-send 'PLAY'"
bindsym XF86AudioPause exec playerctl pause
bindsym XF86AudioNext exec playerctl next

###########################################################
############               PRUEBAS             ############
###########################################################
