-- -*- encoding: utf-8 -*-
-------------------------------------------------------------------------------
--
-- Author:       Raúl Caro Pastorino
-- Email Author: raul@fryntiz.dev
-- Web Author:   http://fryntiz.es
-- gitlab:       https://gitlab.com/fryntiz
-- github:       https://github.com/fryntiz
-- twitter:      https://twitter.com/fryntiz
--
-- Create Date: 2021
-- Project Name: 
-- Description: 
--
-- Dependencies: 
--
-- Revision 0.01 - File Created
-- Additional Comments: 
--
-------------------------------------------------------------------------------
--
-- Copyright (C) 2021  Raúl Caro Pastorino
--
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see <http://www.gnu.org/licenses/>
